define([], function() {
  return {
    NoKeywords: "(none)",
    ForbiddenKeywordsLabel: "Forbidden keywords",
    ForbiddenTagsFieldDescription: "Enter a semi-colon separated list of tags that should not be allowed.",
    ForbiddenTagsFieldLabel: "Forbidden tags",
    AllowGoryFieldLabel: "Allow gory images",
    AllowAdultImagesFieldLabel: "Allow adult images",
    AllowRacyFieldLabel: "Allow racy images",
    AllowLineDrawingFieldLabel: "Allow line drawing images",
    AllowClipartFieldLabel: "Allow clipart images",
    RequirePortraitFieldLabel: "Require portrait photos",
    AnalysisBadLabel: "Your photo does not meet one or more criteria. Try again with a photo that meets the following criteria:",
    NoLabel: "No",
    YesLabel: "Yes",
    GoryLabel: "Gory",
    AdultLabel: "Adult",
    RacyLabel: "Racy",
    LineDrawingLabel: "Line drawing",
    ClipartLabel: "Clip art",
    NumberOfFacesDetectedLabel: "Number of faces detected",
    PortraitLabel: "Portrait",
    PanelInstructionsLabel: "To update your profile photo, use ",
    AnalysisGoodLabel: "Your new photo meets our requirements!",
    GenderLabel: "Gender",
    EstimatedAgeLabel: "Estimated age",
    PanelTitle: "Update your profile photo",
    AnalyzingLabel: "Analyzing your photo...",
    DescriptionLabel: "Description",
    CancelButtonLabel: "Cancel",
    UpdateButtonLabel: "Update",
    SubmitButtonName: "Submit",
    UploadButtonName: "Upload",
    CameraButtonName: "Use camera",
    CameraButtonLabel: "Camera function is disabled for this demo",
    SubmitPhotoDisabledTitle: "Upload a photo before you can submit",
    SubmitPhotoTitle: "Submit your photo",
    MultipleFileTypeErrorLabel: "You can only drop one file at a time",
    UnsupportedFileTypeErrorLabel: "You can only upload photos (e.g.: .PNG, .JPG, .JPEG)",
    UnexpectedErrorLabel: "Unexpected error",
    CommandBarAriaLabel: "Use left and right arrow keys to navigate between commands",
    MoreCommandAriaLabel: "More commands",
    MaxSizeExceededErrorLabel: "Maximum file size exceeded",
    ErrorLabel: "Error",
    CloseLabel: "Close",
    PropertyPaneDescription: "Indicate your requirements to approve a profile photo.",
    BasicGroupName: "Photo requirements",
    InstructionsFieldLabel: "Instructions"
  }
});
